language: node_js
node_js:
  - 8
  - 8.12.0
  - 9
  - 10

before_install:
  - export CHROME_BIN=chromium-browser
services:
  - xvfb

secure: "C/nhSFLipisvngls53qDq/2CHTLFBGmlVfepiBK07dkjtvT41bknDiGjoAKpOs+FUHW1DTmlDivQZbzaXtnp1r8uN4JKjaLkLhpim9R6RkiXrVLxA43ar0fJjeYggVXCxAMPCtB3Wl/Y2mRN8QhNUaSrQHd5+CDJgxds45LPe84="
